const quotes = {
  happy: [
    "Smile like nothing's wrong. It probably is.",
    "Be positive. Reality hates confidence.",
    "Believe in yourself. Evidence is optional.",
    "Good vibes fix everything. Especially nothing.",
    "If it feels wrong, call it growth.",
    "Happiness is denial with better lighting.",
    "You're doing great. Don't investigate.",
    "Confidence first. Consequences later.",
    "Chase your dreams. Trip loudly.",
    "Everything's fine. Say it again.",
    "Trust the process. Don't read the instructions.",
    "Stay optimistic. The details will haunt you later.",
    "Dream big. Trip over the small stuff.",
    "You got this. Probably.",
    "Raise the bar. Walk straight into it.",
    "Celebrate early. Regret on time.",
    "Speak it into existence. Apologize afterward.",
    "Bright side only. Shade optional.",
    "Hustle with jazz hands.",
    "Dance through the red flags.",

    // added
    "Laugh confidently. Confuse reality.",
    "Optimism pairs well with bad decisions.",
    "Smile first. Rationalize later.",
    "Joy is just chaos with good lighting.",
    "Assume it works out. Do not check.",
  ],

  sad: [
    "It's okay to rest. Nothing urgent stays important.",
    "You tried. That counts for something vague.",
    "Lower your expectations. Lower.",
    "Take your time. The deadline will pass without you.",
    "Not every day needs progress. Some need naps.",
    "It's fine to feel lost. Maps are overrated.",
    "Tomorrow is another day. Allegedly.",
    "You don't have to win. You can simply stop.",
    "Crying is emotional maintenance.",
    "Hope is on backorder.",
    "The bar is on the floor. Walk over it.",
    "Let the rain handle the mood board.",
    "Stay in bed. Call it strategy.",
    "Mope softly. Conserve energy.",
    "Let the plot twist find you napping.",
    "Stare at the ceiling. Call it reflection.",
    "Half-finish something. Celebrate the attempt.",
    "Whisper your goals so no one hears you fail.",
    "If it hurts, pause the episode.",
    "Postpone the comeback. It's a vibe.",

    // added
    "Survival is enough today.",
    "Progress is optional. Breathing isn’t.",
    "You don’t need closure to rest.",
    "Healing can wait until tomorrow.",
    "Some days are just placeholders.",
  ],

  angry: [
    "Prove them wrong. Out of pure spite.",
    "Work harder. Make it personal.",
    "Win aggressively. Ask questions never.",
    "Use your rage productively. Or loudly.",
    "They doubted you. Be inconvenient.",
    "Grind like it owes you money.",
    "Dominate your goals. Intimidate your calendar.",
    "Succeed so hard it gets awkward.",
    "Failure is unacceptable. Screaming is optional.",
    "Channel chaos. Deliver results.",
    "Burn out the doubt.",
    "Turn fury into follow-through.",
    "Weaponize your to-do list.",
    "Kick the door down. Replace it later.",
    "Ask forgiveness? No.",
    "Fuel the grind with pure indignation.",
    "Turn obstacles into targets.",
    "Make success an inconvenience for everyone else.",
    "Spite is cheaper than coffee.",
    "If it's in your way, bark at it.",

    // added
    "Outperform out of irritation.",
    "Make results louder than arguments.",
    "Execute with resentment.",
    "Be calm after you win.",
    "Let success do the yelling.",
  ],

  chill: [
    "Breathe in. Breathe out. Ignore everything.",
    "Go with the flow. Preferably away from responsibility.",
    "Relax. Nothing needs immediate effort.",
    "Peace comes from not caring that much.",
    "You'll get to it when it becomes a problem.",
    "Do less. Feel superior.",
    "Stay calm. Let tomorrow panic.",
    "Vibes first. Tasks later.",
    "It's fine to wait. Time loves that.",
    "Zen is just apathy in comfy clothes.",
    "Stretch your goals into next week.",
    "Snooze the universe.",
    "Take five. Then take five more.",
    "Put it on airplane mode. Emotionally.",
    "Let the deadline miss you.",
    "Consider the cloud. Become the cloud.",
    "Sip water. Call it productivity.",
    "Move slow. Trip never.",
    "Inbox zero? Inbox later.",
    "Nap like it's a meeting.",

    // added
    "Nothing urgent deserves this energy.",
    "Delay is a lifestyle.",
    "Soft pace. Hard boundaries.",
    "Calm beats prepared.",
    "Respond slowly. Exist gently.",
  ],

  savage: [
    "Aim lower. Miss anyway.",
    "If at first you don't succeed, redefine success.",
    "Take the L early to free up your afternoon.",
    "You are the plot twist no one asked for.",
    "Turn your red flags into a parade.",
    "Do it badly with confidence.",
    "Set goals you can trip over.",
    "Let them doubt you. They're usually right.",
    "Why plan B? Plan A was chaos.",
    "Schedule your burnout.",
    "Procrastinate loudly.",
    "Your comfort zone has Wi-Fi. Stay there.",
    "You're the main character in a filler episode.",
    "Take the shortcut to the wrong place.",
    "Make mistakes faster for efficiency.",
    "Manifest bare minimum energy.",
    "Break the ice with a flamethrower.",
    "Deliver the bare minimum with a flourish.",
    "Move fast and break your own stuff.",
    "Confidence is 90% volume, 10% luck.",

    // added
    "Set the bar low. Limbo anyway.",
    "Bare minimum. Maximum audacity.",
    "Effort is optional. Commentary isn’t.",
    "Fail forward. Loudly.",
    "Messy, but decisive.",
  ],

  istarii: [
    "Live one day at a time. My mantraa.",
    "Getting on your feet often starts with getting on your knees. Stay humble, keep going.",
    "Self-reflection isn't about blame or perfection; it's about growth. When you look inward, you rise stronger.",
    "At the end of the day, people won't care anyway, so be yourself and dance away.",
    "Find joy inside, let it shine through,\nit'll lift you up when life feels blue.",
    "Tama na yann ayokoo na",
    "AHHAHAHAHHAHA,",
    "Wala na koo maisi[",
    "Booommmm",
    "HAHAHHAHAHAHA",
    "Eyyyy",
    "HAHAHHAHAHAHAH",
    "Dati ka bang Baliw?"
  ],

  dark: [
    "Everything happens for a reason. Usually a bad one.",
    "At least rock bottom has no stairs.",
    "This too shall pass. Like a kidney stone.",
    "You're not behind. You're just off the map.",
    "Life builds character by repeatedly hitting you with a chair.",
    "If nothing matters, stress less accurately.",
    "Failure is just success with worse PR.",
    "Motivation expires faster than dairy.",
    "Some lessons cost more than they teach.",
    "You can't ruin your life if it was never on track.",
    "The void called. It left you on read.",
    "Healing is just trauma with better vocabulary.",
    "Progress is invisible until it's too late.",
    "Your comfort zone is a crime scene.",
    "Hope is a subscription you forgot to cancel.",
    "Life's a joke. Timing is the punchline.",
    "You survived worse. Unfortunately.",
    "Rock bottom is just another floor plan.",
    "Ambition is just anxiety in a suit.",
    "The universe has jokes. You're recurring.",
    "Self-care is damage control.",
    "Your best effort was still noted. Briefly.",
    "Dreams expire if not refrigerated.",
    "You're doing your best. That's concerning.",
    "Existence is a long trial period.",
    "The grind never sleeps. Neither do the regrets.",
    "Everything is temporary. Especially stability.",
    "Success is luck that stayed too long.",
    "Your plan failed. Improv time.",
    'Life said "character development" and meant pain.',
    "Even your backup plan needs a backup plan.",
    "Some people peak emotionally in naps.",
    "Your coping mechanism is impressive.",
    "Nothing builds resilience like repeated disappointment.",
    "You didn't fail. You gathered data.",
    "The bar is low. You still tripped.",
    "Every day is a bold experiment.",
    "The system is rigged. Against vibes.",
    "Stability is a rumor.",
    "Mistakes were made. Mostly by you.",
    "Your inner child needs a nap and a lawyer.",
    "Life keeps respawning the same boss fight.",
    "You're not lost. You're avoiding something.",
    "Confidence is ignorance with good posture.",
    "At least you're consistent.",
    "The universe is gaslighting you.",
    "You're one bad decision from a story arc.",

    // added
    "Optimism is a risky investment.",
    "The lesson will repeat.",
    "Survival mode has no off switch.",
    "This is why you don’t get excited.",
    "Nothing builds character like disappointment.",
  ],
};